---
  version: 1
  schedule:
    type: "simple"
    interval: "1m"
  max-failures: 10
  workflow:
    collect:
      config:
      metrics:
        /intel/psutil/load/load1: {} 
        /intel/psutil/load/load15: {}
        /intel/psutil/load/load5: {}
        /intel/psutil/vm/available: {}
        /intel/psutil/vm/free: {}
        /intel/psutil/vm/used: {}
      publish:
        - plugin_name: "file"
          config:
            file: "/tmp/signalfx_metrics.json"
        - plugin_name: "signalfx"
          config:
            token: "1234ABCD"
